# Generated by Django 3.2.4 on 2021-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pais', models.CharField(choices=[('brasil', 'Brasil'), ('eua', 'EUA'), ('uruguai', 'Uruguai')], default='brasil', max_length=50)),
                ('Estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Fedral'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('SP', 'São Paulo')], default='SP', max_length=50)),
                ('Cidade', models.CharField(choices=[('americana', 'Americana'), ('araraquara', 'Araraquara'), ('belohorizonte', 'Belo Horizonte'), ('curitiba', 'Curitiba')], default='SP', max_length=50)),
                ('CEP', models.CharField(max_length=14)),
                ('Rua', models.CharField(max_length=100)),
                ('Número', models.CharField(max_length=5)),
                ('Complemento', models.CharField(max_length=50)),
            ],
        ),
    ]
