# Generated by Django 3.2.4 on 2021-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210617_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acesso', models.CharField(max_length=60)),
                ('Pais', models.CharField(max_length=60)),
                ('CPF', models.CharField(max_length=14)),
                ('dMail', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=14)),
                ('Estado', models.CharField(choices=[('PR', 'Paraná')], default='PR', max_length=60)),
                ('Cidade', models.CharField(max_length=60)),
                ('Rua', models.CharField(max_length=100)),
                ('Número', models.CharField(max_length=5)),
                ('Complemento', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
