# Generated by Django 3.2.4 on 2021-06-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210618_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rua',
            new_name='models_Bairro',
        ),
        migrations.RenameModel(
            old_name='Cidade',
            new_name='models_Cidade',
        ),
        migrations.RenameModel(
            old_name='Pais',
            new_name='models_Pais',
        ),
        migrations.RenameModel(
            old_name='Bairro',
            new_name='models_Rua',
        ),
        migrations.RenameModel(
            old_name='Uf',
            new_name='models_Uf',
        ),
        migrations.RenameField(
            model_name='models_bairro',
            old_name='Bairro',
            new_name='Cidade',
        ),
        migrations.RenameField(
            model_name='models_rua',
            old_name='Cidade',
            new_name='Bairro',
        ),
    ]
