# Generated by Django 3.2.4 on 2021-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210618_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='cep_big_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=8)),
                ('Uf', models.CharField(max_length=2)),
                ('Cidade', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=100)),
                ('Tipo_logradouro', models.CharField(max_length=30)),
                ('Rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='models_Bairro',
        ),
        migrations.DeleteModel(
            name='models_Cidade',
        ),
        migrations.DeleteModel(
            name='models_Pais',
        ),
        migrations.DeleteModel(
            name='models_Rua',
        ),
        migrations.DeleteModel(
            name='models_Uf',
        ),
        migrations.AlterField(
            model_name='post',
            name='Cidade',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='post',
            name='Estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='Pais',
            field=models.CharField(max_length=7),
        ),
    ]
