# Generated by Django 3.2.4 on 2021-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210622_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='cep_big_users',
            name='Numeros',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
